version: "3.8"

services:
  nginx:
    image: hybula/lookingglass-nginx:1
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8282:80"
    restart: unless-stopped
    volumes:
      - "./style.css:/var/www/html/style.css"

  php-fpm:
    image: hybula/lookingglass-php:1
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - "./config.php:/var/www/html/config.php"
      - "./custom.html.php:/var/www/html/custom.html.php"
      - "./custom.post.php:/var/www/html/custom.post.php"
